# Generated by Django 4.2.2 on 2023-08-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0003_dbcampaign_dbcampaign_home_dbcampaign_user_dbhome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbanketa',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbcampaign', verbose_name='ID Кампании'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='home_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbhome', verbose_name='ID дома'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='note',
            field=models.TextField(null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='open_door',
            field=models.BooleanField(default=False, verbose_name='Открыли дверь'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='published',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата опроса'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='room',
            field=models.CharField(max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbstate', verbose_name='Реакция жильцов'),
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя'),
        ),
        migrations.AddField(
            model_name='dbcampaign',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название кампании'),
        ),
        migrations.AddField(
            model_name='dbcampaign',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя'),
        ),
        migrations.AddField(
            model_name='dbcampaign_home',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbcampaign', verbose_name='ID Кампании'),
        ),
        migrations.AddField(
            model_name='dbcampaign_home',
            name='home_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbhome', verbose_name='ID дома'),
        ),
        migrations.AddField(
            model_name='dbcampaign_user',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbcampaign', verbose_name='ID Кампании'),
        ),
        migrations.AddField(
            model_name='dbcampaign_user',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя'),
        ),
        migrations.AddField(
            model_name='dbhome',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='dbhome',
            name='cnt_entrance',
            field=models.IntegerField(default=0, verbose_name='Количество подъездов'),
        ),
        migrations.AddField(
            model_name='dbhome',
            name='cnt_rooms',
            field=models.IntegerField(default=0, verbose_name='Количество квартир'),
        ),
        migrations.AddField(
            model_name='dbhome',
            name='home',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='dbhome',
            name='street',
            field=models.CharField(db_index=True, default='', max_length=250, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='dbstate',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Реакция жильцов'),
        ),
    ]
