# Generated by Django 4.2.2 on 2023-08-13 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_dbaddress_dbcampaign_address_remove_dbanketa_home_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcampaign_address',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbaddress', verbose_name='ID дома'),
        ),
        migrations.AddField(
            model_name='dbcampaign_address',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbcampaign', verbose_name='ID Кампании'),
        ),
    ]
