# Generated by Django 4.2.2 on 2023-08-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbAddress',
        ),
    ]
