# Generated by Django 4.2.2 on 2023-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('home', models.CharField(max_length=50, verbose_name='Дом')),
                ('cnt_entrances', models.IntegerField(verbose_name='Количество подъездов')),
                ('cnt_rooms', models.IntegerField(verbose_name='Количество квартир')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
                'ordering': ['city'],
            },
        ),
    ]
