# Generated by Django 4.2.2 on 2023-06-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BdCompany',
            new_name='DbCompany',
        ),
    ]
