# Generated by Django 4.2.2 on 2023-08-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_dbanketa_campaign_id_dbanketa_home_id_dbanketa_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('home', models.CharField(max_length=50, verbose_name='Дом')),
                ('cnt_entrances', models.IntegerField(verbose_name='Количество подъездов')),
                ('cnt_rooms', models.IntegerField(verbose_name='Количество квартир')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='DBCampaign_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связь Кампании с адресом дома',
            },
        ),
        migrations.RemoveField(
            model_name='dbanketa',
            name='home_id',
        ),
        migrations.DeleteModel(
            name='DBCampaign_home',
        ),
        migrations.DeleteModel(
            name='DBHome',
        ),
        migrations.AddField(
            model_name='dbanketa',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='campaign.dbaddress', verbose_name='ID дома'),
        ),
    ]
